name: C/C++ CI # The name of the workflow

on: # The trigger for the workflow
  push: # When you push to any branch
    branches: [ main ] # Only for the main branch
  pull_request: # When you create or update a pull request
    branches: [ main ] # Only for the main branch

jobs: # The jobs for the workflow
  build-and-unittest: # The name of the job
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest # The operating system to run the job on
    steps: # The steps for the job
      - name: Checkout # The name of the step
        # uses: actions/checkout@v2 # The action to use for the step
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src
            test
      - name: Install dependencies # The name of the step
        run: sudo apt-get install -y cmake lcov cppcheck # The command to run for the step
      - name: Install gtest
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt
      - name: Run custom build script
        run: bash build.sh test
      - name: Run unit tests
        run: bash build.sh test
      - name: Generate coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          genhtml coverage.info --output-directory out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info # The coverage report file generated by gcov or lcov
          slug: adrian-soch/attitude_check
          exclude: "test"
